version: '3.4'

services:
  aspwebsite:
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 #;https://+:443
      - LANG=C.UTF-8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    env_file:
      - env_mongo.env
  mongodb:
    restart: always
    volumes:
      - .runtime/db:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - env_mongo.env